name: Provision

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to provision"
        required: true
        default: "dev"

jobs:
  linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ">= 20"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-${{ matrix.os }}-${{ matrix.node-version }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint files
        run: npm run lint
  provision:
    runs-on: ubuntu-latest
    needs: linting
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: OIDC Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Provision Resources
        run: |

          ./script/devops.sh provision --env ${{ github.event.inputs.environment }}
